#!/usr/bin/env bash

cd obj
make clean
make

cd ../test_codes
clang -c -emit-llvm example"$1".c -o example"$1".bc
opt -load ../obj/FunctionArgumentInstantiation/libHello.so -hello  -deadargelim example"$1".bc -o example"$1".hello.bc
llvm-dis example"$1".hello.bc -o example"$1".hello.ll

llc -filetype=obj example"$1".hello.bc
clang example"$1".hello.o

echo "Result after transform:"
./a.out

echo "Original reuslt:"
clang example"$1".c
./a.out
